name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "*.py controller/"
          version: "21.5b1"
