name: CheckBlackFormatting

on: [pull_request]

jobs:
  check-black-formatting:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "*.py controller/"
          version: "22.3.0"
